[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "yokogawa-cv8000-utils"
version = "0.2.0"
description = "Process output data from Yokogawa Cell Voyager CV8000"
readme = "README.md"
requires-python = ">=3.10"
license = {text = "MIT"}
dependencies = [
    "dask",
    "numpy",
    "pandas",
    "pydantic>=2",
    "tifffile",
    "tqdm",
    "typer",
    "xarray",
    "xmltodict",
]

[project.scripts]
compile-cv8000 = "compiler.cli:app"

[tool.setuptools.packages.find]
where = ["src"]

[tool.black]
line-length = 88

[tool.isort]
profile = "black"
